export const COLOR_EXTENSION_MAP: {[key: string]: string;} = {
    pdf: "#ffb3ba" ,
    docx: "#ffdfba" ,
    doc: "#ffffba" ,
    pptx: "#baffc9" ,
    ppt: "#bae1ff" ,
    xlsx: "#edc3c3" ,
    xls: "#fad0b9" ,
    mpeg: "#f4f2c3" ,
    jpeg: "#c3edcc" ,
    jpg: "#c3cded" ,
    png: "#ffd4e5" ,
    gif: "#d4ffea" ,
    txt: "#eecbff" ,
    zip: "#feffa3" ,
    rar: "#dbdcff" ,
    mp3: "#d1dcfc" ,
    mp4: "#a3bcfa" ,
    mov: "#fceef5" ,
    avi: "#d1dcfc" ,
    wav: "#ffdeeb" ,
    wma: "#f8bde4" ,
    scss: "#fca2f8" ,
    sass: "#e67df7" ,
    css: "	#ba73ea" ,
    html: "#a8e6cf" ,
    vue: "#dcedc1" ,
    vb: "#ffd3b6" ,
    sql: "#ffaaa5" ,
    pl: "	#ff8b94" ,
    lua: "	#e1ffe9" ,
    hs: "#c2fdd9" ,
    h: "	#95ffd6" ,
    cmd: "#76ffe2" ,
    bat: "#35ffef" ,
    ps1: "	#d4fff8" ,
    sh: "	#bef7ee" ,
    rs: "	#a9ece2" ,
    kotlin: "	#7fdacc" ,
    swift: "	#61ccbb" ,
    php: "	#b2a8f2" ,
    go: "	#a696ea" ,
    cs: "#9a91d4" ,
    cpp: "#9587c3" ,
    c: "#8c74a5" ,
    rb: "#ae5d5d" ,
    java: "	#ffd9e3" ,
    py: "	#f5d3cd" ,
    tsx: "	#ffdab9" ,
    ts: "#ffd98c" ,
    jsx: "	#eeeeee" ,
    js: "	#cfe2f3" ,
    csv: "	#c1e3b3" ,
    json: "	#f4d5d5" ,
    otf: "#aaaaaa" ,
    ttf: "	#0b1b4d" ,
    ai: "	#115390" ,
    psd: "	#b4b4b4" ,
    dng: "	#ecd48d" ,
    exe: "	#f4f4e6" ,
    svg: "	#ffb38a" ,
    aac: "#f8e078" ,
    m4a: "#81a163" ,
    md: "#046669",
    yml: "	#67356d",
    crdownload: "ff00ff",
    env: "fff000"
}